[build-system]
requires      = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "doc_extract"
version = "0.0.1"
description = "Extracts docstrings from a repo and allows annotating them."
authors = ["Terrence Reilly <terrencepreilly@gmail.com>"]
license = "MIT"
repository = "https://github.com/akaihola/darglint2"
keywords = ["utils", "documentation"]
include = ["doc_extract", "static"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI pproved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Intended Audience :: Developers",
]

[tool.poetry.scripts]
doc_extract = "doc_extract.driver:main"

[tool.poetry.dependencies]
python = "^3.7"
darglint2 = {path = "../.."}
