import numpy.bnf

from darglint2.parse.grammar import (
    BaseGrammar,
    P,
)


Grammar: LongDescriptionGrammar

start: <long-description>


<long-description>
    ::= <line> <newlines> <long-description>
    | <line> <newlines>
    | <line>
