[build-system]
requires      = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bnf_to_cnf"
version = "0.1.0"
description = "Converts BNF notation to CNF, as a python class."
authors = ["Terrence Reilly <terrencepreilly@gmail.com>"]
license = "MIT"
repository = "https://github.com/akaihola/darglint2"
keywords = ["grammar", "bnf", "cnf"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Software Development :: Compilers",
    "License :: OSI pproved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Intended Audience :: Developers",
]

[tool.poetry.scripts]
bnf_to_cnf = "bnf_to_cnf.driver:main"

[tool.poetry.dependencies]
python      = "^3.7"
lark-parser = "^0.7.8"
