.phony: all
all:
	docker build -t darglint2-36 -f Dockerfile.test36 . && \
	docker build -t darglint2-37 -f Dockerfile.test37 . && \
	docker build -t darglint2-38 -f Dockerfile.test38 . && \
	docker build -t darglint2-39 -f Dockerfile.test39 .
